name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkouy
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/guthub-action@v6